### ISSUE TITLE
Generar jugada

### ISSUE THREAD

**Issue by dantemogni** [AleRosales/TP-Grupo21#1]
### Faltaría esto para la segunda entrega:

> El jugador cargado, “jugará contra la PC”, la misma tendrá cartones aleatorios, tantos cartones como se haya seleccionado en el paso anterior. 
> Una vez lista la PC y el Jugador empiezan a salir números de la bolsa (salen numeros aleatorios y sin repetir), se debe ir mostrando la evolución de los cartones con cada número que sale. El primer jugador que cante Columna, sumará 10 puntos, el primer jugador que cante línea sumará 20 puntos, y el primero que complete un cartón cantará Bingo, sumando 70 puntos. 

#### Hay que sacar la función que muestra la bolsa completa (tiene que mostrar un solo número, y a partir de ahí mostrar los cartones del Jugador y del CPU, marcando con una `X` la pos. donde dicho número salió, así hasta sacar todos los números). Dsp. generar puntaje.

**Comment by AleRosales** [comment]
Ya termine la jugada. Faltaría lo de los puntos. Podríamos también mostrar los cartones de la PC junto a los del jugador como mejora.
